import type { Entity } from "@/types";

export const entities: Entity[] = [
  {
    id: "cn-tc260",
    name_en: "National Technical Committee 260 on Cybersecurity",
    name_local: "全国网络安全标准化技术委员会",
    acronym: "TC260",
    entity_type: "standards_body",
    country: "China",
    city: "Beijing",
    region: "East Asia",
    website: "https://www.tc260.org.cn/",
    focus_areas: ["standards", "model_security", "evaluation", "frontier_ai_safety"],
    summary: "China's cybersecurity standardization committee, influential in generative AI security standards and AI safety/security frameworks.",
    safety_relevance: "Relevant to frontier AI safety through planned standards on AI-enabled cyberattacks, guardrails, embodied AI security, and risk classification.",
    governance_relevance: "Important standards actor in China's implementation-heavy AI governance system.",
    sensitivity_level: "medium",
    confidence_level: "high",
    last_verified: "2026-05-26",
    source_ids: ["concordia-2025"],
    tags: ["standards", "cybersecurity", "China"],
    tier: 1,
  },
  {
    id: "cn-caict",
    name_en: "China Academy of Information and Communications Technology",
    name_local: "中国信息通信研究院",
    acronym: "CAICT",
    entity_type: "evaluation_institution",
    country: "China",
    city: "Beijing",
    region: "East Asia",
    focus_areas: ["evaluation", "standards", "ai_governance", "model_security"],
    summary: "MIIT-affiliated think tank and evaluation actor involved in AI standards, industry coordination, and safety benchmarking.",
    sensitivity_level: "medium",
    confidence_level: "high",
    last_verified: "2026-05-26",
    source_ids: ["concordia-2025"],
    tags: ["evaluation", "industry", "China"],
    tier: 1,
  },
];
